language: swift
osx_image: xcode9.4
cache: cocoapods
podfile: CITest/Podfile
before_install: echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc -
  pod install --project-directory=CITest
script:
- fastlane beta_dev
env:
  global:
    secure: emm5jUvazlViAXhR9N3q8ETwSNd8oFgGQWgILOSrre2y6rMg44Rz295OQCz3cytSuA2FA7wOKMmDTypw41JyrV+Oc2TxPGWuC/sDGSV8CaKSZdzIDts4Tu9b3Nh+uU4NoB3x99PL7vV7yMZ/MOVFr+0eeMRcuyAB1AhldkSFNidzT62YIIDZ/1pAtSk7Pn+y4BATpHp+PAvg89NzNtzlM9mgnLry3n4fWVs1J5Q1re/w2kCnU7DrP4MsKz/KIpURRpjAbOk2Swi2j8mEn/p40RIkcXqKELJMmfS6LUGz4Tpq9LfcLVWotWTru20b/zAKX2Q+W52AzH1lXpHxk2bDqajsNbfBNQFbcJexPHy++/+VKRRG9I8JuYw59jQ8+f4KYC0LmCAcRCrwyGGk/8rFM+oxeTpvyqa08KGkKS3lpZ+8Zxp0euGfo0pvJzO6u7pClhMzJ/mX6hsUTw93nob9T6EvqmVGHYp+Iv0dTRkPB0a2VQhDjMXyTHDBqY++TnCoU/C+rcz9EiWQqlvwjWAq6EL80kBqg4FkHGhz5wHW+/SyYroG7rX3Idzfv/2IG9XTuKVZylTlpMsT21C00yQTrtx3onPHlLSIuTH3iHPjvY0c7qy6WTTQJjwNIxyJ7PVL5ifCALRpWunenUV0ZyP7aocsp8ly00np0gaRXftf18Q=
